name: mickdarling
favicon: null
layout_spectrum: 0.6500918872188777
typography_spectrum: 0.14785984228365123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.8044242805335671
  saturation: 0.3103223252110183
  rhythmicContrast: 0.6649796739220619
purpose: []
